### ISSUE TITLE
hay ^-^

### ISSUE THREAD

**Issue by ANaSHaker** [dhikshith12/Its12#1]
Sorry for the inconvenience

But I first wanted to thank you for making this project open source, because I liked it and benefited a lot from it because of you, especially in how the product categories work, I understood it from you and I wish you much success later

Secondly, I was just wondering when you will end the shopping cart page because when I try to use what you did and send data to Firebase it is successful, but when you call that data, the command does not work. Is there a specific method for that you will use it later or what

Thank you

**Comment by drxddy** [comment]
Nice to see you here @ANaSHaker 
sorry to say this but I stopped building it as I'm facing build issues couldn't figure it out why flutter build apk was failing but it works fine in dev mode
I've recently made an update which gives add to favorites feature it's just the same code to for add to cart

**Comment by drxddy** [comment]
state management is not good as well I'm using Provider for real time state update in UI but rest is default stateless, and statefull widgets and communication among widgets is all over the place it's not good for such a big project I wanted to implement global state store and any child would refer to that state store and that state store would keep data in sync with firestore after every event in the app but I was alone and couldn't make it to the end. Please let me know if you are intrested then I'll create a new repositroy and achieve realtime state changes reflecting in UI, Sorry I was completely off for 2 months now so couldn't check this issue.

**Comment by drxddy** [comment]
cart feature will be added very soon!
